package empresa;
// Generated 2 feb 2022 17:40:51 by Hibernate Tools 5.5.7.Final

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

	private String nomeDepartamento;
	private Integer numDepartamento;

	public Departamento() {
	}

	public Departamento(String nomeDepartamento) {
		this.nomeDepartamento = nomeDepartamento;
	}

	public Departamento(String nomeDepartamento, Integer numDepartamento) {
		this.nomeDepartamento = nomeDepartamento;
		this.numDepartamento = numDepartamento;
	}

	public String getNomeDepartamento() {
		return this.nomeDepartamento;
	}

	public void setNomeDepartamento(String nomeDepartamento) {
		this.nomeDepartamento = nomeDepartamento;
	}

	public Integer getNumDepartamento() {
		return this.numDepartamento;
	}

	public void setNumDepartamento(Integer numDepartamento) {
		this.numDepartamento = numDepartamento;
	}

}
