package empresa;
// Generated 2 feb 2022 17:40:51 by Hibernate Tools 5.5.7.Final

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.SortedSet;
import java.util.TreeSet;

/**
 * Empregado generated by hbm2java
 */
public class Empregado implements java.io.Serializable {

	private String nss;
	private String nome;
	private String apelido1;
	private String apelido2;
	private Float salario;
	private Date dataNacemento;
	private Character sexo;
	//private Set<Integer> telefonos = new HashSet<>();
	//private Set<Telefono> telefonos = new HashSet<>();
	//private Map<Integer, String> telefonos = new HashMap<>();
	//private Collection<Telefono> telefonos = new ArrayList<>();
	private List<Telefono> telefonos = new ArrayList<>();
	//private Collection<Horas> horasExtra = new ArrayList<>();
	private SortedSet<Horas> horasExtra = new TreeSet<>();
	private Domicilio domicilio;

	public Empregado() {
	}

	public Empregado(String nss) {
		this.nss = nss;
	}

	public Empregado(String nss, String nome, String apelido1, String apelido2, Float salario, Date dataNacemento,
			Character sexo) {
		this.nss = nss;
		this.nome = nome;
		this.apelido1 = apelido1;
		this.apelido2 = apelido2;
		this.salario = salario;
		this.dataNacemento = dataNacemento;
		this.sexo = sexo;
	}

	public String getNss() {
		return this.nss;
	}

	public void setNss(String nss) {
		this.nss = nss;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getApelido1() {
		return this.apelido1;
	}

	public void setApelido1(String apelido1) {
		this.apelido1 = apelido1;
	}

	public String getApelido2() {
		return this.apelido2;
	}

	public void setApelido2(String apelido2) {
		this.apelido2 = apelido2;
	}

	public Float getSalario() {
		return this.salario;
	}

	public void setSalario(Float salario) {
		this.salario = salario;
	}

	public Date getDataNacemento() {
		return this.dataNacemento;
	}

	public void setDataNacemento(Date dataNacemento) {
		this.dataNacemento = dataNacemento;
	}

	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

//	public Set<Integer> getTelefonos() {
//		return telefonos;
//	}
//
//	public void setTelefonos(Set<Integer> telefonos) {
//		this.telefonos = telefonos;
//	}

//	public Set<Telefono> getTelefonos() {
//		return telefonos;
//	}
//
//	public void setTelefonos(Set<Telefono> telefonos) {
//		this.telefonos = telefonos;
//	}

//	public Map<Integer, String> getTelefonos() {
//		return telefonos;
//	}
//
//	public void setTelefonos(Map<Integer, String> telefonos) {
//		this.telefonos = telefonos;
//	}

//	public Collection<Telefono> getTelefonos() {
//		return telefonos;
//	}
//
//	public void setTelefonos(Collection<Telefono> telefonos) {
//		this.telefonos = telefonos;
//	}
	
	public List<Telefono> getTelefonos() {
		return telefonos;
	}

	public void setTelefonos(List<Telefono> telefonos) {
		this.telefonos = telefonos;
	}

//	public Collection<Horas> getHorasExtra() {
//		return horasExtra;
//	}
//
//	public void setHorasExtra(Collection<Horas> horasExtra) {
//		this.horasExtra = horasExtra;
//	}

	public SortedSet<Horas> getHorasExtra() {
		return horasExtra;
	}

	public void setHorasExtra(SortedSet<Horas> horasExtra) {
		this.horasExtra = horasExtra;
	}
	
	public Domicilio getDomicilio() {
		return domicilio;
	}
	
	public void setDomicilio(Domicilio domicilio) {
		this.domicilio = domicilio;
	}
	
	

}
